[package]
name = "birlscript"
version = "2.0.0-alpha"
authors = ["Rafael R Nakano <lazpeng@gmail.com>"]

description = "Interpretador da linguagem BIRLSCRIPT"
repository = "https://github.com/birlscript/birlscript"
