[package]
name = "birlscript"
version = "0.1.3"
authors = ["Rafael <lazpeng@gmail.com>"]

description = "Interpretador da linguagem BIRLSCRIPT"
repository = "https://github.com/lazpeng/birl"

[dependencies]
